### ISSUE TITLE
Discussion: support for saving locally to IndexedDB

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/penumbra#64]
It would be cool if visitors to Privacy Centers with previous access requests can continue viewing their export, even after it's gone from our systems.

IndexedDB allows for Blob storage. Could be interesting.

(A) Is this a worthwhile feature?
(B) Does it belong here or in the Privacy Center code?

**Comment by michaelfarrell76** [comment]
hm not sure about this. feels to me like its outside the scope of penumbra. secondly, feels like a fair amount of work for something thats not really needed and not adding too much value. we would have to worry about 

1. storage limitations to ensure we aren't try to store massive files here
2. the UX experience -- say i do an access request, it stores the data, then i perform an erasure and then the data persists on the browser because of this, it could feel like the erasure didnt actually happen (a fair number of corner cases).
3. we hold around the download report for 2 weeks anyways which is a fairly long time, if someone wants to see their data again we should strive for it to be easy and quick to perform another access request
4. in the case someone wants their data for a longer period of time, we should make it easier for them to view that data offline,

although it seems like a cool piece of technology, my vote is to not pursue

**Comment by bencmbrook** [comment]
Agreed - at best it's a distant feature

**Comment by michaelfarrell76** [comment]
eli loves localForage
